name: Build docker image and push
on:
  workflow_call:
    secrets:
      USER_TOKEN:
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.USER_TOKEN }}

      # Initialize and configure Docker Buildx, a modern building toolkit.
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        # Authenticate against the specified container registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Generate metadata like tags and labels for the Docker image.
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=tag
            type=semver,pattern={{version}}
      # Push the image to the registry, excluding push during pull requests.
      - name: Push docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "VERSION=${{github.ref_name}}"
  fetch-sync-pr:
    needs: build
    name: Fetching PR Number of sync PR 
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get-pr-number.outputs.pr_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.USER_TOKEN }}
      # Check if the sync branch already exists
      - name: Get PR Number
        id: get-pr-number
        run: |
          PR_NUMBER=$(gh pr list --search "🔄 Master into develop" --json number -q ".[0].number")
          echo "PR number: $PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
  rebase-sync-pr:
    needs: fetch-sync-pr
    runs-on: ubuntu-latest
    if: ${{ needs.fetch-sync-pr.outputs.pr_number != '' }}
    steps:
      - name: Echo pr_number
        run: echo "${{ needs.fetch-sync-pr.outputs.pr_number }}"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.USER_TOKEN }}
      - name: Use PR Number
        run: gh pr update-branch ${{ needs.fetch-sync-pr.outputs.pr_number }} --rebase
  create-sync-pr:
    needs: fetch-sync-pr
    runs-on: ubuntu-latest
    if: ${{ needs.fetch-sync-pr.outputs.pr_number == '' }}
    steps:
      - name: Echo pr_number
        run: echo "${{ needs.fetch-sync-pr.outputs.pr_number }}"
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.USER_TOKEN }}
      # This should only be runed on master 
      - name: Create pull request to sync master and develop
        run: gh pr create -B develop -H master --title "🔄 Master into develop" --body "Auto generated pr to merge master into develop"